import{i as a}from"./assets/vendor-8e8cd629.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&e(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function e(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();function l(o){const n=`https://pixabay.com/api/?${new URLSearchParams(o).toString()}`;return fetch(n).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).then(e=>e.hits.length===0?(a.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!"}),null):e).catch(e=>{throw e})}function u(o){console.log(o);const s=document.querySelector(".gallery");s.innerHTML="";const n=o.map(e=>`<li class="item-ul"><img src="${e.webformatURL}" alt="${e.tags}"><div class"about-img-div"><p class="description-img">Likes</p>
<p class="description-img">Views</p>
<p class="description-img">Comments</p>
<p class="description-img">Downloads</p>
<span class="description-value">${e.likes}</span
><span class="description-value">${e.views}</span
><span class="description-value">${e.comments}</span
><span class="description-value">${e.downloads}</span></div></li>`).join("");s.insertAdjacentHTML("beforeend",n)}const c=document.querySelector(".form");c.addEventListener("submit",p);function p(o){if(o.preventDefault(),c.elements[0].value.trim()==="")a.error({title:"",message:"Enter some text!"});else{const n={key:"45056360-0d73312e4ecad0bc63c18ca30",q:c.elements[0].value.trim(),image_type:"photo",orientation:"horizontal",safesearch:!0};l(n).then(e=>{e&&u(e.hits)}).catch(e=>{console.error("Error fetching images:",e)})}}
//# sourceMappingURL=commonHelpers.js.map
